export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const SYNC_CURRECT_TRANSACTION = 'SYNC_CURRECT_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const START_TRANSACTION = 'START_TRANSACTION';

